In [ ]:
import numpy as np

arr = np.array(10)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
zeros_arr = np.zeros(5)
print(zeros_arr)
print(zeros_arr.dtype)

[0. 0. 0. 0. 0.]
float64


In [6]:
zeros_arr = np.zeros(5).astype(int)
print(zeros_arr)
print(zeros_arr.dtype)

[0 0 0 0 0]
int64


In [24]:


arr = np.full((3, 4), 5 )
print(arr)
print(arr.shape)
print(arr.dtype)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
(3, 4)
int64


In [33]:
arr = np.full((3, 4),5)
arr, arr.shape, arr.dtype


(array([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]),
 (3, 4),
 dtype('int64'))

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
np.swapaxes(arr, 0, 1)



array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
arr = np.array([4, 7, 1, 9, 3])
print(arr.max()) 


9


In [50]:
arr = np.array([4, 7, 1, 9, 3])
print(arr.reshape(5,1)) 

[[4]
 [7]
 [1]
 [9]
 [3]]


In [64]:
arr = np.array([[4, 7, 1, 9, 3] , [2,8,9,5,6]])
arr.sort(axis=1)
print(arr)

[[1 3 4 7 9]
 [2 5 6 8 9]]
