In [ ]:
import numpy as np

arr = np.array(10)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
zeros_arr = np.zeros(5)
print(zeros_arr)
print(zeros_arr.dtype)

[0. 0. 0. 0. 0.]
float64


In [6]:
zeros_arr = np.zeros(5).astype(int)
print(zeros_arr)
print(zeros_arr.dtype)

[0 0 0 0 0]
int64


In [24]:


arr = np.full((3, 4), 5 )
print(arr)
print(arr.shape)
print(arr.dtype)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
(3, 4)
int64


In [33]:
arr = np.full((3, 4),5)
arr, arr.shape, arr.dtype


(array([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]),
 (3, 4),
 dtype('int64'))

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
np.swapaxes(arr, 0, 1)



array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
arr = np.array([4, 7, 1, 9, 3])
print(arr.max()) 


9


In [50]:
arr = np.array([4, 7, 1, 9, 3])
print(arr.reshape(5,1)) 

[[4]
 [7]
 [1]
 [9]
 [3]]


In [64]:
arr = np.array([[4, 7, 1, 9, 3] , [2,8,9,5,6]])
arr.sort(axis=1)
print(arr)

[[1 3 4 7 9]
 [2 5 6 8 9]]


In [ ]:
import numpy as np

array2 = np.array([[1,2,3,4],[5,6,7,8]])            #creating two dimension array
array1 = np.array([1,2,3,4])                        #creating an array
array1                                              #printing an array
array1.dtype                                        #printing the datatype
array1.ndim                                         #printing the dimension
array2.ndim
array2.shape                                        #numbers of rows and columns
array1.reshape(2,2)                                 #convert dimension of an array
print(array1[0])                                    #array indexing
print(array1[-1])                                   #to access last element of array
array3 = np.arange(0,11)                            #printing array using arange function
print(array3)  
print(np.argmax(array1))                            #index of maximum element in array
print(np.argmin(array2))                            #index of minimum element in array
print(np.diff(array1))                              #difference between consecutive elements
print(np.linspace(0,1,6))                           #evenly spaced values between two numbers


1
4
[ 0  1  2  3  4  5  6  7  8  9 10]
3
0
[1 1 1]
[0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
add = x + y                                         #add elements of array
sub = x - y                                         #subtract elements of array
mul = x * y                                         #multiple elements of array
div = x / y                                         #divide elements of array
print(add)
print(sub)
print(mul)
print(div)

[5 7 9]
[-3 -3 -3]
